### PR TITLE
Refix tree loadings

### LINKED ISSUE #211: Problems with plotLoadings()
Hey,

There appears to be some issue with the function `plotLoadings()`. It does not respond to the parameters `ncomponents` or `n` and fails to color features. 

Testing with another dataset (GlobalPatterns) replicates the same issue of not responding to the parameters `ncomponents` or `n`, but it will correctly color features. 

Below is a reproducible example with SprockettTHData

```r
# Libraries
library(mia)
library(miaViz)
library(microbiomeDataSets)

# Load data
tse <- SprockettTHData()
# Subset
tse <- tse[, tse[["Sample_Type"]] %in% c("Feces")]
tse <- tse[, tse[["Age_Class"]] %in% c("Infant")]

# Agglomerate and apply transformations
altExp(tse, "Phylum") <- agglomerateByRank(tse, "Phylum")
tse <- transformAssay(tse, method = "relabundance", altexp = "Phylum")
tse <- transformAssay(
  tse,
  method = "clr",
  pseudocount = TRUE,
  altexp = "Phylum"
)

# Perform dbRDA
altExp(tse, "Phylum") <- addRDA(
  altExp(tse, "Phylum"),
  assay.type = "clr",
  method = "euclidean",
  formula = x ~ Age_Months + Country,
  na.action = na.exclude
)

# Plot
p_load <- plotLoadings(
  altExp(tse, "Phylum"),
  dimred = "RDA",
  layout = "heatmap",
  ncomponents = 2,
  n = 20,
  add.tree = TRUE
)

p_load
```

### PR DESCRIPTION
**Pull request by raivo-otus**
Resubmit of fixes applied in #212 WITHOUT autoformatting and unrelated fixes to links

### CODE REVIEW

File: DESCRIPTION [hunk 1]
```diff
@@ -66,6 +66,7 @@ Suggests:
     bluster,
     circlize,
     ComplexHeatmap,
+    GenomeInfoDb,
```
Comment (TuomasBorman) [inline DESCRIPTION]: Is this needed?

File: R/plotLoadings.R
Comment (TuomasBorman) [inline R/plotLoadings.R:1]: Wasn't there more improvements? Include all functional improvements related to plotloadings that were in the old PR. (The plot looked very nice in that PR if I remember correctly)

**Review by TuomasBorman — CHANGES_REQUESTED** [review]

File: R/plotLoadings.R
Comment (raivo-otus) [reply R/plotLoadings.R:1]: I'll double back. Likely missed something, have since disabled all autoformating on save to prevent this mess in the future.

File: DESCRIPTION (hunk 1 above)
Comment (raivo-otus) [reply DESCRIPTION]: No, strictly for this no. But checks were throwing annoying errors that this fixed. Along with the correct links that where in the previous PR but omitted here.

Comment (TuomasBorman) [reply DESCRIPTION]: Can you check what these errors were?

The package is not directly related to miaViz, I think. The dependency comes probably from somewhere else, meaning that the dependency errors should be fixed there.

This is for controlling that the dependency list does not expand too much (the list is already too big)

**Comment by raivo-otus** [comment]
Should be the rest of the changes. Still feels like I might have missed something but can't spot. The function still needs some work I think, it throws many warning on invalid object types when plotting..

File: DESCRIPTION (hunk 1 above)
Comment (raivo-otus) [reply DESCRIPTION]: Seems it is not needed anymore. Removed.

**Review by TuomasBorman — APPROVED** [review]
Thanks!
